# @name login
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "john.doe@email.com",
    "password": "password"
}

### SET TOKEN
@auth_token = {{login.response.body.data.access_token}}

# @name fetchUserProfile
GET http://127.0.0.1:8000/api/users/profile/5eadef29-3798-4510-8f12-5828dcb14ecd
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}