# @name forgotPassword
POST http://127.0.0.1:8000/api/auth/forgot-password
Content-Type: application/json
Accept: application/json

{
    "email": "john.doe@email.com"
}

###

# @name verifyForgotPasswordOTP
POST http://127.0.0.1:8000/api/auth/verify-forgot-password-otp
Content-Type: application/json
Accept: application/json

{
    "email": "john.doe@email.com",
    "otp": "123456"
}

###

# @name resendForgotPasswordOTP
POST http://127.0.0.1:8000/api/auth/resend-forgot-password-otp
Content-Type: application/json
Accept: application/json

{
    "email": "john.doe@email.com"
}

###

# @name resetPassword
POST http://127.0.0.1:8000/api/auth/reset-password
Content-Type: application/json
Accept: application/json

{
    "email": "john.doe@email.com",
    "password": "password",
    "password_confirmation": "password",
    "token": "ZM4zw2WTBB73GlPh"
}

