# @name resetPasword
POST http://127.0.0.1:8000/api/auth/reset-password
Content-Type: application/json
Accept: application/json

{
    "email": "srikanto7.acharya@email.com",
    "password": "password",
    "token": "123456"
}