# @name register
POST http://127.0.0.1:8000/api/auth/register
Content-Type: application/json
Accept: application/json

{
    "name": "john5",
    "email": "srikanto5.acharya@email.com",
    "password": "password",
    "password_confirmation": "password"
}

###
# @name login
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "srikanto.acharya@email.com",
    "password": "password"
}

### SET TOKEN
@refresh_token = {{login.response.body.data.refresh_token}}


# @name refreshToken
GET http://127.0.0.1:8000/api/auth/refresh
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{refresh_token}}

### SET TOKEN
@auth_token = {{login.response.body.data.access_token}}


###
# @name getAuthUser
GET http://127.0.0.1:8000/api/auth/user
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}


###
# @name logout
GET http://127.0.0.1:8000/api/auth/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}


###
# @name getAuthUser
GET http://127.0.0.1:8000/api/auth/user
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

