# @name createPost
POST http://127.0.0.1:8000/api/posts
Content-Type: application/json
Accept: application/json

{
    "body": "This is the content of the post.",
    "location": "Location details",
    "privacy_id": 1,
    "attachments": [
        {
            "type": "image",
            "url": "http://example.com/image.jpg",
            "thumbnail_url": "http://example.com/image_thumb.jpg",
            "description": "An image description",
            "duration": null
        }
    ]
}
