# @name createPostWithNewAttachments
POST http://127.0.0.1:8000/api/posts
Content-Type: application/json
Accept: application/json

{
    "body": "Content of the new post.",
    "location": "Location details",
    "privacy_id": 1,
    "attachments": [
        {
            "type": "image",
            "url": "http://example.com/image.jpg",
            "thumbnail_url": "http://example.com/image_thumb.jpg",
            "description": "Image description",
            "duration": null
        },
        {
            "type": "document",
            "url": "http://example.com/document.pdf",
            "thumbnail_url": null,
            "description": "Document description",
            "duration": null
        }
    ]
}
