# @name login
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "john.doe@email.com",
    "password": "password"
}


### SET TOKEN
@auth_token = {{login.response.body.data.access_token}}


# @name likePost
POST http://127.0.0.1:8000/api/posts/44f99ab3-7b1c-4faf-ba5a-124450441ea8/like
Accept: application/json
Authorization: Bearer {{auth_token}}
