# @name uploadFile
POST http://127.0.0.1:8000/api/upload
Content-Type: multipart/form-data
Accept: application/json

--boundary
Content-Disposition: form-data; name="file"; filename="example.jpg"
Content-Type: image/jpeg

(binary data here)
--boundary--
