# @name login
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "john.doe@email.com",
    "password": "password"
}

### SET TOKEN
@auth_token = {{login.response.body.data.access_token}}

# @name fetchUserProfile
GET http://127.0.0.1:8000/api/users/profile/b61f4f92-c2ae-40c6-a268-bd173c774da4
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}



### SET TOKEN
# @name fetchUserProfile
GET http://127.0.0.1:8000/api/users/profile/60b7ca58-eb8c-4f56-be31-571cc94d7c34
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}