# @name login
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "john.doe@email.com",
    "password": "password"
}

### SET TOKEN
@auth_token = {{login.response.body.data.access_token}}

# @name fetchUserProfile
GET http://127.0.0.1:8000/api/users/profile/2c6704ff-7c83-4b77-90b3-00a75fd71e10
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}



### SET TOKEN
# @name fetchUserProfile
GET http://127.0.0.1:8000/api/users/profile/678d3fdc-f319-4f96-b9a0-80391225f0e8
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}