# @name login
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "john.doe@email.com",
    "password": "password"
}


### SET TOKEN
@auth_token = {{login.response.body.data.access_token}}


# @name createPostWithNewAttachments
POST http://127.0.0.1:8000/api/posts
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=------------------------abcdefg

--------------------------abcdefg
Content-Disposition: form-data; name="post_text"

This is the body of the post.
--------------------------abcdefg
Content-Disposition: form-data; name="location"

Location info
--------------------------abcdefg
Content-Disposition: form-data; name="privacy_id"

01
--------------------------abcdefg
Content-Disposition: form-data; name="attachments[]"; filename="radish.jpg"
Content-Type: image/jpeg

< ./../../assets/radish.jpg
--------------------------abcdefg
Content-Disposition: form-data; name="attachments[]"; filename="old.png"
Content-Type: image/png

< ./../../assets/old.png
--------------------------abcdefg--
