# @name login
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "john.doe@email.com",
    "password": "password"
}


### SET TOKEN
@auth_token = {{login.response.body.data.access_token}}

# @name getPosts
GET http://127.0.0.1:8000/api/users/posts?limit=50&offset=0
Accept: application/json


###
# @name getPosts
GET http://127.0.0.1:8000/api/users/posts?limit=50&offset=0
Accept: application/json
Authorization: Bearer {{auth_token}}
