# @name login
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "john.doe@email.com",
    "password": "password"
}


### SET TOKEN
@auth_token = {{login.response.body.data.access_token}}

# @name getPost
GET http://127.0.0.1:8000/api/posts/f3ab7976-69f9-4ee4-9130-55045f825bb1
Accept: application/json
Authorization: Bearer {{auth_token}}
