# @name login
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "john.doe@email.com",
    "password": "password"
}


### SET TOKEN
@auth_token = {{login.response.body.data.access_token}}

# @name getPost
GET http://127.0.0.1:8000/api/posts/31ed1c4e-74b9-4696-9bea-43604f1efe4c
Accept: application/json
Authorization: Bearer {{auth_token}}
