# @name login
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "john.doe@email.com",
    "password": "password"
}


### SET TOKEN
@auth_token = {{login.response.body.data.access_token}}

###
# @name updatePostWithExistingAttachments
POST http://127.0.0.1:8000/api/posts/update/bdbab76a-eb06-4536-98d7-2ea447ecfc22
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=------------------------abcdefg

--------------------------abcdefg
Content-Disposition: form-data; name="post_text"

This is the body of the post.
--------------------------abcdefg
Content-Disposition: form-data; name="location"

Location info
--------------------------abcdefg
Content-Disposition: form-data; name="privacy_id"

01
--------------------------abcdefg
Content-Disposition: form-data; name="delete_attachments[]"

d4922590-8fb5-4487-935d-37abf6c4a31c
--------------------------abcdefg
Content-Disposition: form-data; name="attachments[]"; filename="radish.jpg"
Content-Type: image/jpeg

< ./../../assets/radish.jpg
--------------------------abcdefg--