# @name login
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "john.doe@email.com",
    "password": "password"
}


### SET TOKEN
@auth_token = {{login.response.body.data.access_token}}


# @name createPostWithNewAttachments
POST http://127.0.0.1:8000/api/v2/posts
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=------------------------abcdefg

--------------------------abcdefg
Content-Disposition: form-data; name="uid"

12345
--------------------------abcdefg
Content-Disposition: form-data; name="body"

This is the body of the post.
--------------------------abcdefg
Content-Disposition: form-data; name="location"

Location info
--------------------------abcdefg
Content-Disposition: form-data; name="privacy_id"

1
--------------------------abcdefg
Content-Disposition: form-data; name="attachments[]"; filename="radish.jpg"
Content-Type: image/jpeg

< ./../../files/radish.jpg
--------------------------abcdefg
Content-Disposition: form-data; name="attachments[]"; filename="old.png"
Content-Type: image/png

< ./../../files/old.png
--------------------------abcdefg--
