# @name login
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "john.doe@email.com",
    "password": "password"
}

### SET TOKEN
@auth_token = {{login.response.body.data.access_token}}


###
# @name uploadFile
POST http://127.0.0.1:8000/api/upload
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=------------------------abcdefg

--------------------------abcdefg
Content-Disposition: form-data; name="file"; filename="radish.jpg"
Content-Type: image/jpg

< ./../upload_files/radish.jpg
--------------------------abcdefg--
