# @name login
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "john.doe@email.com",
    "password": "password"
}

### SET TOKEN
@auth_token = {{login.response.body.data.access_token}}


# Get Following List
GET http://127.0.0.1:8000/api/following/22aa7819-8fc8-486c-9cd8-1143f2c9e06c
Authorization: Bearer {{auth_token}}
Content-Type: application/json
