# @name login
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "john.doe@email.com",
    "password": "password"
}

### SET TOKEN
@auth_token = {{login.response.body.data.access_token}}


# Get Following List
GET http://127.0.0.1:8000/api/following/f079d931-e881-4856-b3ac-b15ece52542e
Authorization: Bearer {{auth_token}}
Content-Type: application/json
